# Generated by Django 3.2.11 on 2022-03-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
        ('exam', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qtype', to='Quiz.qtype'),
        ),
    ]
