# Generated by Django 3.2.11 on 2022-03-18 05:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220317_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_image_path_profile),
        ),
    ]
