# Generated by Django 3.2.11 on 2022-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220131_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=255, verbose_name='Title')),
                ('category_slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('category_short', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('category_createddate', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
