# Generated by Django 3.2.11 on 2022-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cr_id', models.AutoField(db_column='cr_id', primary_key=True, serialize=False)),
                ('cr_title', models.CharField(max_length=255, verbose_name='Title')),
                ('cr_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('cr_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('cr_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('cr_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('cr_categ', models.ManyToManyField(db_column='cr_categ', related_name='courses', to='course.CourseCategory', verbose_name='Category')),
            ],
        ),
    ]
