# Generated by Django 3.2.11 on 2022-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_cr_categ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(db_column='sub_id', primary_key=True, serialize=False)),
                ('sub_title', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('sub_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('sub_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('sub_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sub_course', models.ManyToManyField(db_column='sub_course', null=True, related_name='subject', to='course.CourseCategory', verbose_name='Subject')),
            ],
        ),
    ]
