# Generated by Django 3.2.11 on 2022-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_course',
            field=models.ManyToManyField(db_column='sub_course', null=True, related_name='subject', to='course.Course', verbose_name='Subject'),
        ),
    ]
