# Generated by Django 3.2.11 on 2022-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_subject_sub_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cr_categ',
            field=models.ManyToManyField(db_column='cr_categ', related_name='courses', to='course.CourseCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_course',
            field=models.ManyToManyField(db_column='sub_course', related_name='subject', to='course.Course', verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('top_id', models.AutoField(db_column='top_id', primary_key=True, serialize=False)),
                ('top_title', models.CharField(max_length=255, verbose_name='Title')),
                ('top_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('top_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('top_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('top_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('top_subject', models.ManyToManyField(db_column='sub_categ', related_name='subjects', to='course.Subject', verbose_name='subjects')),
            ],
        ),
    ]
