# Generated by Django 3.2.11 on 2022-02-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220219_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='top_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='top_subject',
            field=models.ManyToManyField(db_column='top_subject', related_name='topics', to='course.Subject', verbose_name='Topic'),
        ),
    ]
