# Generated by Django 3.2.11 on 2022-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qtype',
            fields=[
                ('qt_id', models.AutoField(db_column='qt_id', primary_key=True, serialize=False)),
                ('qt_title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
    ]
