# Generated by Django 3.2.11 on 2022-03-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batchCourse',
            fields=[
                ('bcr_id', models.AutoField(db_column='bcr_id', primary_key=True, serialize=False)),
                ('bcr_title', models.CharField(max_length=255, verbose_name='Title')),
                ('bcr_slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('bcr_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('bcr_long', models.TextField(blank=True, null=True, verbose_name='Long description')),
                ('bcr_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('bcr_categ', models.ManyToManyField(db_column='bcr_categ', related_name='courses', to='course2.batchCategory', verbose_name='Category')),
            ],
        ),
    ]
